# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='country',
            field=models.CharField(default='United States', max_length=200),
            preserve_default=False,
        ),
    ]
