# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_auto_20160426_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('snack', models.CharField(max_length=200)),
                ('snack_type', models.CharField(max_length=200)),
                ('country', models.CharField(default='United States', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
