# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trade_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='trading',
            field=models.BooleanField(default=False),
        ),
    ]
