# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 15:50
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20160509_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
