# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20160509_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='market',
            name='trade_type',
            field=models.CharField(choices=[('Trade', 'Trade'), ('Giving', 'Giving'), ('Holding', 'Holding')], default='Trade', max_length=100),
        ),
    ]
